=== FaculdadeLicenciatura/tiwm22-ti-g02/xml/zoo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
        targetNamespace="http://www.juicers.org"
        xmlns:tns="http://www.juicers.org"
        elementFormDefault="qualified">

    <complexType name="Animal">
            <sequence>
                <element name="Nome" type="string"></element>
                <element name="Descricao">
                    <simpleType>
                        <restriction base="string">
                            <minLength value="200"></minLength>
                        </restriction>
                    </simpleType>
                </element>
                <element name="SmallDesc">
                    <simpleType>
                        <restriction base="string">
                            <maxLength value="200"></maxLength>
                        </restriction>
                    </simpleType>
                </element>
                <element name="Idade">
                <simpleType>
                    <restriction base="int">
                        <maxInclusive value="200"></maxInclusive>
                        <minExclusive value="0"></minExclusive>
                    </restriction>
                </simpleType>
                </element>
                <element name="Foto" type="anyURI"></element>
                <element name="Especie" type="tns:Especie"></element>
            </sequence>
    </complexType>

    <complexType name="Especie">
        <sequence>
            <element name="NomeEspecie" type="string"></element>
            <element name="Tipo">
                <simpleType>
                    <restriction base="token">
                        <enumeration value="Mamífero"></enumeration>
                        <enumeration value="Peixe"></enumeration>
                        <enumeration value="Réptil"></enumeration>
                        <enumeration value="Ave"></enumeration>
                    </restriction>
                </simpleType>
            </element>
            <element name="SubEspecie" type="tns:SubEspecie"></element>
        </sequence>
    </complexType>


    <complexType name="SubEspecie">
        <sequence>
            <element name="NomeSubEspecie" type="string"></element>
            <element name="Local" type="string"></element>
        </sequence>
    </complexType>

    <complexType name="Artigo">
        <sequence>
            <element name="Nome" type="string"></element>
            <element name="Preco" type="decimal"></element>
            <element name="Categoria">
                <simpleType>
                    <restriction base="token">
                        <enumeration value="Felino"></enumeration>
                        <enumeration value="Peixe"></enumeration>
                        <enumeration value="Réptil"></enumeration>
                        <enumeration value="Primata"></enumeration>
                        <enumeration value="Ave"></enumeration>
                        <enumeration value="Bilhete"></enumeration>
                    </restriction>
                </simpleType>
            </element>
            <element name="Quantidade">
                <simpleType>
                    <restriction base="int">
                        <minExclusive value="0"></minExclusive>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
    </complexType>

    <complexType name="Funcionario">
        <sequence>
            <element name="Nome" type="string"></element>
            <element name="Descricao" type="string"></element>
            <element name="Especialidade" type="string"></element>
        </sequence>
    </complexType>

    <complexType name="Morada">
        <sequence>
            <element name="Pais" type="string"></element>
            <element name="Cidade" type="string"></element>
            <element name="CodPostal">
                <simpleType>
                    <restriction base="string">
                        <pattern value="[0-9]{4}-[0-9]{3}"></pattern>
                    </restriction>
                </simpleType>
            </element>
            <element name="AnoFund">
                <simpleType>
                    <restriction base="int">
                        <minInclusive value="1900"></minInclusive>
                    </restriction>
                </simpleType>
            </element>
            <element name="QuantidadeAnimais">
                <simpleType>
                    <restriction base="int">
                        <minInclusive value="1"></minInclusive>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
    </complexType>


    <element name="Zoo">
        <complexType>
            <sequence>
                <element name="Morada" type="tns:Morada" maxOccurs="1"></element>
                <element name="Animais" maxOccurs="1">
                    <complexType>
                        <sequence>
                            <element name="Animal" type="tns:Animal" maxOccurs="unbounded"></element>
                        </sequence>
                    </complexType>
                </element>
                <element name="Funcionarios" maxOccurs="1">
                    <complexType>
                        <sequence>
                            <element name="funcionario" type="tns:Funcionario" maxOccurs="unbounded"></element>
                        </sequence>
                    </complexType>
                </element>
                <element name="Loja" maxOccurs="1">
                    <complexType>
                        <sequence>
                            <element name="Artigo" type="tns:Artigo" maxOccurs="unbounded"></element>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
        </complexType> 
    </element>
</schema>

=== FaculdadeLicenciatura/tiwm22-ti-g02/xml/zoo.xml
<?xml version="1.0" encoding="UTF-8"?>
<Zoo mlns="http://www.juicers.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.juicers.org zoo.xsd">
    <Morada>
        <Pais>Portugal</Pais>
        <Cidade>Porto</Cidade>
        <CodPostal>4440-897</CodPostal>
    </Morada>
    <AnoFund>2022</AnoFund>
    <QuantidadeAnimais>10</QuantidadeAnimais>
    <Animais>
        <Animal>
            <Especie>Gorila</Especie>
            <SubEspecie>Grande</SubEspecie>
            <Nome>King Kong</Nome>
            <Idade>10</Idade>
        </Animal>
        <Animal>
            <Especie>Leão</Especie>
            <SubEspecie>Africano</SubEspecie>
            <Nome>Simba</Nome>
            <Idade>7</Idade>
        </Animal>
        <Animal>
            <Especie>Suricata</Especie>
            <SubEspecie>Pintada</SubEspecie>
            <Nome>Timon</Nome>
            <Idade>5</Idade>
        </Animal>
        <Animal>
            <Especie>Javali</Especie>
            <SubEspecie>Africano</SubEspecie>
            <Nome>Pumba</Nome>
            <Idade>7</Idade>
        </Animal>
        <Animal>
            <Especie>Veado</Especie>
            <SubEspecie>Vermelho</SubEspecie>
            <Nome>Bambi</Nome>
            <Idade>10</Idade>
        </Animal>
        <Animal>
            <Especie>Elefante</Especie>
            <SubEspecie>Africano</SubEspecie>
            <Nome>Dumbo</Nome>
            <Idade>15</Idade>
        </Animal>
        <Animal>
            <Especie>Cavalo</Especie>
            <SubEspecie>Mustangue</SubEspecie>
            <Nome>Spirit</Nome>
            <Idade>18</Idade>
        </Animal>
        <Animal>
            <Especie>Peixe</Especie>
            <SubEspecie>Palhaço</SubEspecie>
            <Nome>Nemo</Nome>
            <Idade>5</Idade>
        </Animal>
        <Animal>
            <Especie>Urso</Especie>
            <SubEspecie>Panda</SubEspecie>
            <Nome>Pô</Nome>
            <Idade>15</Idade>
        </Animal>
        <Animal>
            <Especie>Ornitorrinco</Especie>
            <SubEspecie>Castanho</SubEspecie>
            <Nome>Perry</Nome>
            <Idade>18</Idade>
        </Animal>
        <Especie>
            <Nome>Gorila</Nome>
            <Descricao>É um gorila</Descricao>
            <Local>Floresta</Local>
        </Especie>
        <Especie>
            <Nome>Leão</Nome>
            <Descricao>É um Leão</Descricao>
            <Local>Selva</Local>
        </Especie>
        <Especie>
            <Nome>Elefante</Nome>
            <Descricao>É um elefante</Descricao>
            <Local>Floresta</Local>
        </Especie>
        <Especie>
            <Nome>Peixe</Nome>
            <Descricao>É um Peixe</Descricao>
            <Local>Mar</Local>
        </Especie>
        <SubEspecie>
            <Nome>Africano</Nome>
            <Especie>Leão</Especie>
            <Descricao>Leão que vive em Africa</Descricao>
        </SubEspecie>
        <SubEspecie>
            <Nome>Panda</Nome>
            <Especie>Urso</Especie>
            <Descricao>Meste das martes Marciais</Descricao>
        </SubEspecie>
        <SubEspecie>
            <Nome>Gorila</Nome>
            <Especie>Grande</Especie>
            <Descricao>Gorila grande mas simpático</Descricao>
        </SubEspecie>
    </Animais>
    <Funcionarios>
        <funcionário>
            <Nome>Henrique</Nome>
            <Descricao>Jogar ás escondidas</Descricao>
            <Especialidade>Felinos</Especialidade>
        </funcionário>
        <funcionário>
            <Nome>Alexandre</Nome>
            <Descricao>Jogar airsoft ou lá o que é</Descricao>
            <Especialidade>Caçador</Especialidade>
        </funcionário>
        <funcionário>
            <Nome>Garrido</Nome>
            <Descricao>Estagiário</Descricao>
            <Especialidade>Ainda por apurar</Especialidade>
        </funcionário>
    </Funcionarios>
    <Loja>
        <Artigo>
            <Nome>Pluxe Leão</Nome>
            <Preco>20.00</Preco>
            <Categoria>Felino</Categoria>
            <Quantidade>30</Quantidade>
        </Artigo>
        <Artigo>
            <Nome>Pluxe Nemo</Nome>
            <Preco>20.00</Preco>
            <Categoria>Peixe</Categoria>
            <Quantidade>20</Quantidade>
        </Artigo>
        <Artigo>
            <Nome>Pluxe Tigre</Nome>
            <Preco>20.00</Preco>
            <Categoria>Felino</Categoria>
            <Quantidade>50</Quantidade>
        </Artigo>
        <Artigo>
            <Nome>Bilhete Adulto</Nome>
            <Preco>29.99</Preco>
            <Categoria>Bilhete</Categoria>
            <Quantidade>100</Quantidade>
        </Artigo>
        <Artigo>
            <Nome>Bilhete Idoso</Nome>
            <Preco>19.99</Preco>
            <Categoria>Bilhete</Categoria>
            <Quantidade>100</Quantidade>
        </Artigo>
        <Artigo>
            <Nome>Bilhete Criança</Nome>
            <Preco>9.99</Preco>
            <Categoria>Bilhete</Categoria>
            <Quantidade>100</Quantidade>
        </Artigo>
    </Loja>
</Zoo>
